### ISSUE TITLE
[Feature] Add new target 'draft', which uploads but does not publish

### ISSUE THREAD

**Issue by dword-design** [GabrielDuarteM/semantic-release-chrome#60]
# Issue

- [x] I have searched the [issues](https://github.com/GabrielDuarteM/semantic-release-chrome/issues) of this repository and believe that this is not a duplicate.

## Your Environment

- `semantic-release-chrome` version:
- `node` version: 0.0.0-development
- `npm` (or `yarn`) version: Yarn 1.21.1

## Feature proposal

Problem with the current Chrome Web Store is that the extension get's into a pending review state. In this state you cannot upload new versions. I propose to add a new target 'draft', which omits the publishing step, so only uploads the extension archive.

Branch is already implemented. The implementation is pretty straight-forward.

**Comment by melink14** [comment]
This is especially useful when you have a change that requires updating CWS metadata like changing permissions or collecting user data.
