### ISSUE TITLE
HTTP Error 400 when Publishing

### ISSUE THREAD

**Issue by keplersj** [GabrielDuarteM/semantic-release-chrome#7]
I've been trying to use this plugin to publish an extension to the Chrome Webstore, and haven't had a successful run yet. I have followed the Authentication instructions in the README, setting the variables in the Travis CI settings page, and have configured Travis to run semantic-release after tests pass on master.

[Repo](https://github.com/keplersj/cises)
[Travis Build](https://travis-ci.org/keplersj/cises/jobs/506391803)
[Chrome Webstore Link](
https://chrome.google.com/webstore/detail/pebfiklbcoioidmjoelliojmfamipfnn/publish-accepted) - first version submitted manually

Not really sure what else might help here. If you need any other info please let me know. I think this is a really cool plugin for semantic-release, and when paired with [semantic-release-firefox](https://github.com/felixfbecker/semantic-release-firefox) presents an awesome opportunity to make developing browser extensions that are built using the WebExtensions APIs easier.

**Comment by keplersj** [comment]
Sorry, I figured it out. I butchered the very final step of the Authentication instructions. I was getting Error 400 because I set `GOOGLE_REFRESH_TOKEN` to the JSON Object copied to the clipboard, instead of the value of `refresh_token` in the JSON Object. Once I set `GOOGLE_REFRESH_TOKEN` to the value of `refresh_token` the publish step was successful.

Sorry for the spam.

**Comment by alandtse** [comment]
Just for people who run into the 400, another cause is requiring to provide information in the Privacy tab. I'm not sure if there's a way for the component to tell if it's at this state so it doesn't actually break the release run.
